# Container by docker-compose for Pangea Pondera Lab
version: "3"
	services:
	      PonderaLabContainer:
	        image: "jupyter/all-spark-notebook"
	        environment:
	            - JUPYTER_ENABLE_LAB=${JUPYTER_ENABLE_LAB:-yes}
	            - GRANT_SUDO=yes
	        user: root
	        volumes:
	            - type: bind
	              source: ${VOLUMES:-/datalake/ponderalab}
	              target: "/home/jovyan/ponderalab"
	        ports:
	            - "8181:8888"
        command: "start.sh jupyter lab --LabApp.token='PangeaPonderaLab'" # Access Token 
