# Container by docker-compose for data lake  
version: "3"
	services:
	      LCiD-ideamaps-Paloma-Merodio:
	        image: "jupyter/all-spark-notebook:2021-09-27"
	        environment:
	            - JUPYTER_ENABLE_LAB=${JUPYTER_ENABLE_LAB:-yes}
	            - GRANT_SUDO=yes
	        user: root
	        volumes:
	            - type: bind
	              source: ${VOLUMES:-/datalake/ponderalab}
	              target: "/home/jovyan/datos_ideamaps"
	        ports:
	            - "8123:8888"
        command: "start.sh jupyter lab --LabApp.token='PangeaPonderaLab'" # Comando para token
